Repository Likelion-13th-EGSBI/Likelion-13th-EGSBI-FE, pull requests merged in 2025-08, with the labels that each got.

#40 design: 로그인 및 회원가입 페이지 작업 완료(#9)
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/css/init.css
  front/src/css/login.css
  front/src/css/signuppage.css
  front/src/imgs/mainlogo.png
  front/src/pages/LoginPage.jsx
  front/src/pages/SignupPage.jsx
  front/src/pages/init.jsx
Labels: UI, frontend

#42 chore: PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: frontend, chore

#41 design: 마이페이지 작업 완료(#4)
  front/src/App.js
  front/src/css/mypage.css
  front/src/pages/MyPage.jsx
Labels: UI, frontend

#43 design: 행사 등록 페이지 및 사이드바, 상단바 구현 완료
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/components/Layout.jsx
  front/src/components/Sidebar.jsx
  front/src/components/TopBar.jsx
  front/src/css/eventupload.css
  front/src/css/layout.css
  front/src/css/sidebar.css
  front/src/css/topbar.css
  front/src/pages/EventUpload.jsx
Labels: UI, frontend

#46 feat: 구독 페이지 구현 (SubscribePage)
  front/src/components/HostCard.jsx
  front/src/css/hostcard.css
  front/src/css/subscribe.css
  front/src/pages/HostDetail.jsx
  front/src/pages/SubscribePage.jsx
Labels: UI, frontend

#58 fix: app.js 중복 선언 제거
  front/src/App.js
Labels: fix, frontend

#63 feat: 내가 등록한 행사 UI개발 및 API 연결
  front/src/App.js
  front/src/css/myuploadevent.css
  front/src/pages/MyPage.jsx
  front/src/pages/MyUploadEvent.jsx
Labels: feature, UI, frontend

#66 design: 임시 메인페이지 작업
  front/src/App.js
  front/src/components/Sidebar.jsx
  front/src/css/initmain.css
  front/src/pages/InitMain.jsx
Labels: UI, frontend

#72 chore: 파비콘 및 tilte 수정
  front/public/favicon.ico
  front/public/index.html
Labels: frontend, chore

#74 refactor: 지도 infowindow 수정
  front/src/css/bookmark-joined.css
Labels: refactor

#77 refactor: 내가 참여한행사
  front/src/css/bookmarkedevents.css
  front/src/css/joinedevents.css
  front/src/css/review-modal.css
  front/src/pages/BookmarkedEvents.jsx
  front/src/pages/JoinedEvents.jsx
Labels: UI, refactor, frontend

#82 [feat] MainPage UI 작업
  front/src/App.js
  front/src/css/mainpage.css
  front/src/pages/MainPage.jsx
Labels: UI, frontend

#85 refactor: 행사 업로드 API 연결 수정 및 QR 체크인 연결완료(#76,#83)
  front/src/App.js
  front/src/css/checkinpage.css
  front/src/css/eventupload.css
  front/src/pages/CheckInPage.jsx
  front/src/pages/EventUpload.jsx
  front/src/pages/LoginPage.jsx
Labels: feature, refactor, frontend

#91 feat: 체크인 API 연결(#84)
  front/src/pages/CheckInPage.jsx
Labels: feature, frontend

#98 refactor: 프로필카드 부분 api 수정
  front/src/css/mypage.css
  front/src/pages/MyPage.jsx
Labels: feature, frontend

#97 editprofile api 연결완료
  front/src/css/editprofile.css
  front/src/pages/EditProfile.jsx
Labels: feature, frontend

#100 refactor: 프로필 수정 + 마이페이지 api 수정
  front/src/pages/EditProfile.jsx
  front/src/pages/MyPage.jsx
Labels: feature, frontend

#101 feat: 내가 등록한 행사 리뷰 보기 API 연결(#96)
  front/src/css/myuploadevent.css
  front/src/pages/MyUploadEvent.jsx
Labels: feature, frontend

#104 refactor: EventCard markdown 적용
  front/src/components/EventCard.jsx
Labels: refactor, frontend

#105 feat: 이메일 인증 페이지 추가(#102)
  front/src/App.js
  front/src/css/emailverification.css
  front/src/css/signuppage.css
  front/src/pages/EmailVerificationPage.jsx
  front/src/pages/SignupPage.jsx
Labels: feature, frontend

#122 refactor: mypage UI 수정
  front/src/css/mypage.css
  front/src/pages/MyPage.jsx
Labels: refactor, frontend

#123 refactor: 내가 등록한 행사 QR 보기 추가
  front/src/css/myuploadevent.css
  front/src/pages/MyUploadEvent.jsx
Labels: refactor, frontend

#125 refactor: bookmarkedevents 상단 헤더 추가
  front/src/css/bookmarkedevents.css
  front/src/pages/BookmarkedEvents.jsx
Labels: refactor, frontend

#132 refactor: 사이드바 ui 수정
  front/src/components/HostCard.jsx
  front/src/components/Sidebar.jsx
Labels: refactor, frontend
